// Generated by tools/web-parts/generate-play-parts.mjs — do not edit by hand.
import type { PartFrameBox } from "@/schema/types";
import document from "./frameBoxes.generated.json";
const boxes = document as unknown as { boxes: PartFrameBox[] };
/** Build-mode alignment bounds of each part's bracket, from the original's `frame` sprites. */
export const PART_FRAME_BOXES: ReadonlyMap<number, PartFrameBox> = new Map(
  boxes.boxes.map((box) => [box.partTypeId, box]),
);
