// Generated by tools/web-parts/generate-play-parts.mjs — do not edit by hand.
import document from "./playParts.generated.json";
import type { PartContentDocument } from "@/schema/types";
export const PLAY_PARTS = document as unknown as PartContentDocument;
