export { PLAY_PARTS } from "./playParts.generated";

export const PALETTE = [
  { partTypeId: 4, label: "猪" },
  { partTypeId: 1, label: "木块" },
  { partTypeId: 7, label: "铁轮" },
  { partTypeId: 8, label: "发动机" },
  { partTypeId: 9, label: "TNT" },
  { partTypeId: 10, label: "气球" },
  { partTypeId: 11, label: "风扇" },
  { partTypeId: 12, label: "弹簧" },
  { partTypeId: 13, label: "火箭" },
  { partTypeId: 14, label: "小轮" },
  { partTypeId: 15, label: "大轮" },
  { partTypeId: 16, label: "粘性轮" },
  { partTypeId: 17, label: "马达轮" },
  { partTypeId: 18, label: "金属箱" },
  { partTypeId: 19, label: "双气球" },
  { partTypeId: 20, label: "三气球" },
  { partTypeId: 21, label: "沙袋" },
  { partTypeId: 22, label: "双沙袋" },
  { partTypeId: 23, label: "三沙袋" },
  { partTypeId: 24, label: "猪王" },
  { partTypeId: 25, label: "黑汽水" },
  { partTypeId: 26, label: "绿汽水" },
  { partTypeId: 27, label: "蛋" },
  { partTypeId: 28, label: "拳套" },
  { partTypeId: 30, label: "红烟花" },
  { partTypeId: 31, label: "木滑翔翼" },
  { partTypeId: 32, label: "金属滑翔翼" },
  { partTypeId: 33, label: "木尾翼" },
  { partTypeId: 34, label: "金属尾翼" },
  { partTypeId: 35, label: "黑伞" },
  { partTypeId: 36, label: "电伞" },
  { partTypeId: 37, label: "旋翼" },
  { partTypeId: 38, label: "螺旋桨" },
  { partTypeId: 39, label: "齿轮杆" },
  { partTypeId: 40, label: "风箱" },
  { partTypeId: 41, label: "绳索" },
  { partTypeId: 42, label: "炸药" },
  { partTypeId: 43, label: "拆卸器" },
  { partTypeId: 44, label: "手电筒" },
  { partTypeId: 45, label: "探照灯" },
  { partTypeId: 46, label: "抓钩" },
  { partTypeId: 270, label: "小发动机" },
  { partTypeId: 271, label: "大发动机" },
] as const;
export const GOAL_ZONE = { minX: 12, minY: -0.5, maxX: 16, maxY: 2.5 };
export const MAP_BOUNDS = { minX: -30, minY: -12, maxX: 30, maxY: 30 };
