import type { PartContentDocument } from "@/schema/types";

export const PLAY_PARTS: PartContentDocument = {
  format: "pigforge.part-content",
  schemaVersion: 1,
  contentVersion: "pigforge-base-content-v1",
  parts: [
    { partTypeId: 1, name: "wooden-block", mode: "dynamic", mass: 1, shapes: [{ kind: "box", halfExtents: [0.5, 0.5, 0.5] }] },
    { partTypeId: 3, name: "ball-weight", mode: "dynamic", mass: 2.5, shapes: [{ kind: "sphere", radius: 0.4 }] },
    { partTypeId: 4, name: "pig", mode: "dynamic", mass: 1, capabilities: { pig: true }, shapes: [{ kind: "sphere", radius: 0.42 }] },
    { partTypeId: 7, name: "wheel", mode: "dynamic", mass: 0.5, capabilities: { wheel: true }, shapes: [{ kind: "sphere", radius: 0.33 }] },
    { partTypeId: 8, name: "engine", mode: "dynamic", mass: 1.2, capabilities: { motor: { thrustPerTick: 2, directionX: 1 } }, shapes: [{ kind: "box", halfExtents: [0.45, 0.45, 0.5] }] },
    { partTypeId: 9, name: "tnt", mode: "dynamic", mass: 1, capabilities: { tnt: { fuseTicks: 5 } }, shapes: [{ kind: "box", halfExtents: [0.475, 0.475, 0.475] }] },
    { partTypeId: 10, name: "balloon", mode: "dynamic", mass: 0.3, capabilities: { balloon: 1.5 }, shapes: [{ kind: "sphere", radius: 0.5 }] },
    { partTypeId: 11, name: "fan", mode: "dynamic", mass: 0.8, capabilities: { fan: { thrustPerTick: 1.2, directionX: 1, directionY: 0 } }, shapes: [{ kind: "box", halfExtents: [0.225, 0.5, 0.5] }] },
    { partTypeId: 12, name: "spring", mode: "dynamic", mass: 0.6, capabilities: { spring: 12 }, shapes: [{ kind: "box", halfExtents: [0.35, 0.1, 0.5] }] },
    { partTypeId: 13, name: "rocket", mode: "dynamic", mass: 0.9, capabilities: { rocket: { thrustPerTick: 4, directionX: 1, durationTicks: 60 } }, shapes: [{ kind: "box", halfExtents: [0.35, 0.15, 0.5] }] },
    { partTypeId: 14, name: "small-wheel", mode: "dynamic", mass: 0.3, capabilities: { wheel: true }, shapes: [{ kind: "sphere", radius: 0.18 }] },
    { partTypeId: 15, name: "cart-wheel", mode: "dynamic", mass: 1.2, capabilities: { wheel: true }, shapes: [{ kind: "sphere", radius: 0.36 }] },
    { partTypeId: 16, name: "sticky-wheel", mode: "dynamic", mass: 0.6, capabilities: { wheel: true }, shapes: [{ kind: "sphere", radius: 0.45 }] },
    { partTypeId: 17, name: "motor-wheel", mode: "dynamic", mass: 0.8, capabilities: { wheel: true, motor: { thrustPerTick: 2.2, directionX: 1 } }, shapes: [{ kind: "sphere", radius: 0.45 }] },
    { partTypeId: 18, name: "metal-box", mode: "dynamic", mass: 2, capabilities: {}, shapes: [{ kind: "box", halfExtents: [0.5, 0.5, 0.5] }] },
    { partTypeId: 19, name: "balloon-double", mode: "dynamic", mass: 0.6, capabilities: { balloon: 3 }, shapes: [{ kind: "sphere", radius: 0.5 }] },
    { partTypeId: 20, name: "balloon-triple", mode: "dynamic", mass: 0.9, capabilities: { balloon: 4.5 }, shapes: [{ kind: "sphere", radius: 0.5 }] },
    { partTypeId: 21, name: "sandbag", mode: "dynamic", mass: 3, shapes: [{ kind: "sphere", radius: 0.13 }] },
    { partTypeId: 22, name: "sandbag-double", mode: "dynamic", mass: 6, shapes: [{ kind: "sphere", radius: 0.13 }] },
    { partTypeId: 23, name: "sandbag-triple", mode: "dynamic", mass: 9, shapes: [{ kind: "sphere", radius: 0.13 }] },
    { partTypeId: 24, name: "king-pig", mode: "dynamic", mass: 1.2, capabilities: { pig: true }, shapes: [{ kind: "box", halfExtents: [1.05, 0.9, 0.5] }] },
    { partTypeId: 25, name: "soda-bottle-black", mode: "dynamic", mass: 0.8, capabilities: { rocket: { thrustPerTick: 8, directionX: 1, directionY: 0, durationTicks: 30 } }, shapes: [{ kind: "box", halfExtents: [0.375, 0.2, 0.5] }] },
    { partTypeId: 26, name: "soda-bottle-green", mode: "dynamic", mass: 0.8, capabilities: { rocket: { thrustPerTick: 6, directionX: 0, directionY: 1, durationTicks: 40 } }, shapes: [{ kind: "box", halfExtents: [0.375, 0.2, 0.5] }] },
    { partTypeId: 27, name: "egg", mode: "dynamic", mass: 0.4, capabilities: { egg: true }, shapes: [{ kind: "box", halfExtents: [0.3, 0.425, 0.3] }] },
    { partTypeId: 28, name: "boxing-glove", mode: "dynamic", mass: 0.8, capabilities: { spring: 25 }, shapes: [{ kind: "box", halfExtents: [0.5, 0.5, 0.5] }] },
    { partTypeId: 29, name: "firework-blue", mode: "dynamic", mass: 0.9, capabilities: { rocket: { thrustPerTick: 4, directionX: 0, directionY: 1, durationTicks: 45, explodeRadius: 3, explodeImpulse: 14 } }, shapes: [{ kind: "box", halfExtents: [0.25, 0.45, 0.25] }] },
    { partTypeId: 30, name: "firework-red", mode: "dynamic", mass: 0.9, capabilities: { rocket: { thrustPerTick: 6, directionX: 0, directionY: 1, durationTicks: 30, explodeRadius: 4, explodeImpulse: 20 } }, shapes: [{ kind: "box", halfExtents: [0.35, 0.15, 0.5] }] },
    { partTypeId: 31, name: "wooden-glider-wing", mode: "dynamic", mass: 0.6, capabilities: { wing: { liftCoef: 0.05, maxLift: 6 } }, shapes: [{ kind: "box", halfExtents: [0.95, 0.3061, 0.75] }] },
    { partTypeId: 32, name: "metal-glider-wing", mode: "dynamic", mass: 0.9, capabilities: { wing: { liftCoef: 0.08, maxLift: 10 } }, shapes: [{ kind: "box", halfExtents: [0.9, 0.3061, 0.75] }] },
    { partTypeId: 33, name: "wooden-tail-wing", mode: "dynamic", mass: 0.5, capabilities: { tail: 0.03 }, shapes: [{ kind: "box", halfExtents: [0.425, 0.375, 0.5] }] },
    { partTypeId: 34, name: "metal-tail-wing", mode: "dynamic", mass: 0.7, capabilities: { tail: 0.05 }, shapes: [{ kind: "box", halfExtents: [0.5, 0.425, 0.5] }] },
    { partTypeId: 35, name: "black-umbrella", mode: "dynamic", mass: 0.5, capabilities: { umbrella: 0.2 }, shapes: [{ kind: "box", halfExtents: [0.5, 0.475, 0.5] }] },
    { partTypeId: 36, name: "electric-umbrella", mode: "dynamic", mass: 0.7, capabilities: { umbrella: 0.35 }, shapes: [{ kind: "box", halfExtents: [0.5, 0.475, 0.5] }] },
    { partTypeId: 37, name: "rotor", mode: "dynamic", mass: 0.7, capabilities: { balloon: 3.5 }, shapes: [{ kind: "box", halfExtents: [1.275, 0.44, 0.5] }] },
    { partTypeId: 38, name: "propeller", mode: "dynamic", mass: 0.9, capabilities: { wheel: true, motor: { thrustPerTick: 2.5, directionX: 1 } }, shapes: [{ kind: "box", halfExtents: [0.14, 0.5, 0.5] }] },
    { partTypeId: 39, name: "gearbox-lever", mode: "dynamic", mass: 0.7, capabilities: { gearbox: true }, shapes: [{ kind: "box", halfExtents: [0.45, 0.45, 0.5] }] },
    { partTypeId: 40, name: "bellows", mode: "dynamic", mass: 0.6, capabilities: { bellows: 8 }, shapes: [{ kind: "box", halfExtents: [0.4, 0.35, 0.5] }] },
    { partTypeId: 41, name: "rope", mode: "dynamic", mass: 0.3, shapes: [{ kind: "box", halfExtents: [1.5, 0.06, 0.06] }] },
    { partTypeId: 42, name: "dynamite", mode: "dynamic", mass: 1, capabilities: { tnt: { fuseTicks: 1 } }, shapes: [{ kind: "box", halfExtents: [0.4, 0.25, 0.3] }] },
    { partTypeId: 43, name: "detacher", mode: "dynamic", mass: 0.5, capabilities: { detacher: true }, shapes: [{ kind: "box", halfExtents: [0.5305, 0.5297, 0.5] }] },
    { partTypeId: 44, name: "flashlight", mode: "dynamic", mass: 0.4, capabilities: { light: 3 }, shapes: [{ kind: "box", halfExtents: [0.335, 0.42, 0.5] }] },
    { partTypeId: 45, name: "spotlight", mode: "dynamic", mass: 0.8, capabilities: { light: 5 }, shapes: [{ kind: "box", halfExtents: [0.3, 0.2, 0.2] }] },
    { partTypeId: 46, name: "grappling-hook", mode: "dynamic", mass: 0.7, capabilities: { grapple: { impulse: 22, directionX: 0.70710678, directionY: 0.70710678 } }, shapes: [{ kind: "box", halfExtents: [0.35, 0.24, 0.5] }] },
    { partTypeId: 6, name: "ramp-plank", mode: "static", mass: 0, shapes: [{ kind: "box", halfExtents: [6.0, 0.25, 1.0] }] },
    { partTypeId: 47, name: "tnt-nitro", variantOf: 9, variantName: "Nitro TNT", mode: "dynamic", mass: 1, capabilities: { tnt: { fuseTicks: 5 } }, shapes: [{ kind: "box", halfExtents: [0.475, 0.475, 0.475] }] },
    { partTypeId: 48, name: "tnt-bomb", variantOf: 9, variantName: "Bomb TNT", mode: "dynamic", mass: 1, capabilities: { tnt: { fuseTicks: 5 } }, shapes: [{ kind: "box", halfExtents: [0.475, 0.475, 0.475] }] },
    { partTypeId: 49, name: "tnt-gift", variantOf: 9, variantName: "Gift TNT", mode: "dynamic", mass: 1, capabilities: { tnt: { fuseTicks: 5 } }, shapes: [{ kind: "box", halfExtents: [0.475, 0.475, 0.475] }] },
    { partTypeId: 50, name: "tnt-pumpkin", variantOf: 9, variantName: "Pumpkin TNT", mode: "dynamic", mass: 1, capabilities: { tnt: { fuseTicks: 5 } }, shapes: [{ kind: "box", halfExtents: [0.475, 0.475, 0.475] }] },
  ],
};

export const PALETTE = [
  { partTypeId: 4, label: "猪" },
  { partTypeId: 1, label: "木块" },
  { partTypeId: 3, label: "配重球" },
  { partTypeId: 7, label: "轮子" },
  { partTypeId: 8, label: "发动机" },
  { partTypeId: 9, label: "TNT" },
  { partTypeId: 10, label: "气球" },
  { partTypeId: 11, label: "风扇" },
  { partTypeId: 12, label: "弹簧" },
  { partTypeId: 13, label: "火箭" },
  { partTypeId: 14, label: "小轮" },
  { partTypeId: 15, label: "大轮" },
  { partTypeId: 16, label: "粘性轮" },
  { partTypeId: 17, label: "马达轮" },
  { partTypeId: 18, label: "金属箱" },
  { partTypeId: 19, label: "双气球" },
  { partTypeId: 20, label: "三气球" },
  { partTypeId: 21, label: "沙袋" },
  { partTypeId: 22, label: "双沙袋" },
  { partTypeId: 23, label: "三沙袋" },
  { partTypeId: 24, label: "猪王" },
  { partTypeId: 25, label: "黑汽水" },
  { partTypeId: 26, label: "绿汽水" },
  { partTypeId: 27, label: "蛋" },
  { partTypeId: 28, label: "拳套" },
  { partTypeId: 29, label: "蓝烟花" },
  { partTypeId: 30, label: "红烟花" },
  { partTypeId: 31, label: "木滑翔翼" },
  { partTypeId: 32, label: "金属滑翔翼" },
  { partTypeId: 33, label: "木尾翼" },
  { partTypeId: 34, label: "金属尾翼" },
  { partTypeId: 35, label: "黑伞" },
  { partTypeId: 36, label: "电伞" },
  { partTypeId: 37, label: "旋翼" },
  { partTypeId: 38, label: "螺旋桨" },
  { partTypeId: 39, label: "齿轮杆" },
  { partTypeId: 40, label: "风箱" },
  { partTypeId: 41, label: "绳索" },
  { partTypeId: 43, label: "拆卸器" },
  { partTypeId: 44, label: "手电筒" },
  { partTypeId: 45, label: "探照灯" },
  { partTypeId: 46, label: "抓钩" },
] as const;
export const GOAL_ZONE = { minX: 12, minY: -0.5, maxX: 16, maxY: 2.5 };
export const MAP_BOUNDS = { minX: -30, minY: -12, maxX: 30, maxY: 30 };
