<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../PigForge.Physics.Abstractions/PigForge.Physics.Abstractions.csproj" />
    <PackageReference Include="BepuPhysics" Version="2.4.0" />
  </ItemGroup>
</Project>
