/**
 * Animation composition: one opaque state object the renderer keeps outside Vue reactivity and
 * advances once per rendered frame with the animation clock's step.
 *
 * Every descriptor comes from the manifest (`part-textures.json` v3, gitignored, generated by
 * `tools/bple-textures/extract.mjs`): a fan/rotor blade's spin, a pig's face clips and its
 * expression thresholds. Nothing here feeds the wire, the replay document or the state hash —
 * animation is presentation only, and the server stays the authority on pose and switch state.
 *
 * See `docs/specs/part-texture-animation.md` § 运行时契约.
 */

import type { DrawEntity, PartContentDocument, PartDefinition } from "@/schema/types";
import type { PartSprite, PartTexture, PartTextureSet } from "../atlas";
import {
  createClipPlayer,
  createExpressionState,
  playClip,
  speedReference,
  stepClip,
  stepExpression,
  type ClipPlayer,
  type ExpressionState,
} from "./frames";
import { createSpinState, foreshorten, stepSpin, type SpinState } from "./spin";

/** Clip players and the expression machine of one entity. */
interface EntityFrames {
  /** spriteIndex -> clip player (only sprites whose manifest entry carries clips). */
  sprites: Map<number, ClipPlayer>;
  expression?: ExpressionState;
  /** Last clip request this entity played, so a repeat request restarts the clip. */
  requestId: number;
}

export interface AnimationState {
  /** entityId -> spriteIndex -> spin runtime (fan, propeller and rotor blades). */
  spins: Map<number, Map<number, SpinState>>;
  /** entityId -> frame runtimes (clip players, and the pig expression machine). */
  frames: Map<number, EntityFrames>;
  /** Entities of the last update, so a dropped one drops its animation (mark and sweep). */
  live: Set<number>;
  /** Injected blink roll; the app passes `Math.random`, tests pin it. */
  random: () => number;
}

/** The pose the renderer blits for one sprite: the manifest sprite, or its clip's current frame. */
export interface SpritePose {
  sprite: PartSprite;
  /** Rotation added on top of the sprite's own `rot` (radians, counter-clockwise, +y up). */
  rot: number;
  /** Scale about the sprite's own centre; the spin foreshortening writes one axis. */
  scaleX: number;
  scaleY: number;
}

/** Σ thrust of a body's active motors and Σ mass of every part on it: the two inputs of vRef. */
interface BodyTotals {
  thrust: number;
  mass: number;
}

// Reused across calls so the hot path allocates nothing; the animation state of a canvas is
// advanced from one place, so module-scope scratch cannot be observed from another frame.
const BODY_TOTALS = new Map<number, BodyTotals>();
const PART_INDEX = new Map<number, PartDefinition>();
let pose: SpritePose | null = null;

export function createAnimationState(random: () => number = Math.random): AnimationState {
  return { spins: new Map(), frames: new Map(), live: new Set(), random };
}

/**
 * Drops every entity's animation state: the clock restarts on the frame the view starts
 * running again (Start/RESET, or resuming a replay), so angles return to zero, clips to
 * `Normal` and the blink timer to a fresh roll.
 */
export function resetAnimations(state: AnimationState): void {
  state.spins.clear();
  state.frames.clear();
  state.live.clear();
}

/**
 * Advances every live entity's animation by `dtSeconds` (0 = frozen: build mode, a paused
 * replay, a preview part). Previews (`bodyId` 0) never get state.
 */
export function updateAnimations(
  state: AnimationState,
  entities: readonly DrawEntity[],
  content: PartContentDocument | null,
  textures: PartTextureSet | null,
  dtSeconds: number,
): void {
  sweepRemoved(state, entities);
  if (!(dtSeconds > 0) || textures === null) return;
  const totals = collectBodyTotals(entities, content);
  for (const entity of entities) {
    if (entity.bodyId === 0) continue;
    const texture = textures.parts.get(entity.partTypeId);
    if (!texture) continue;
    const clip = stepEntityExpression(state, texture, entity, totals, dtSeconds);
    // A fresh request (a new expression, a blink, a hit) must replay the clip from its first
    // frame even when the name is unchanged — the original's `SpriteAnimation.Play` queues it.
    let restart = false;
    if (clip !== undefined) {
      const frames = entityFramesOf(state, entity.entityId);
      const requested = frames.expression?.requestId ?? 0;
      restart = frames.requestId !== requested;
      frames.requestId = requested;
    }
    for (let index = 0; index < texture.sprites.length; index += 1) {
      const sprite = texture.sprites[index];
      if (sprite.spin) {
        // The snapshot's switch bit is the only driver, exactly as on the server.
        stepSpin(spinOf(state, entity.entityId, index), sprite.spin.maxDegreesPerSecond, entity.active, dtSeconds);
      }
      if (!sprite.clips) continue;
      const player = playerOf(state, entity.entityId, index, sprite);
      // Every sprite of the part plays the same clip name, like `m_childAnimations` does.
      if (clip !== undefined && (restart || player.clip !== clip)) playClip(player, clip);
      stepClip(player, dtSeconds);
    }
  }
}

/**
 * Pose of one sprite. The returned object is reused between calls, so the renderer must consume
 * it before asking for the next sprite (`draw.ts` draws immediately); a sprite without an
 * animation descriptor gets `{ sprite, rot: 0, scaleX: 1, scaleY: 1 }` — an exact pass-through
 * of the manifest art.
 */
export function poseFor(
  state: AnimationState,
  entity: DrawEntity,
  spriteIndex: number,
  sprite: PartSprite,
): SpritePose {
  const result = pose ?? (pose = { sprite, rot: 0, scaleX: 1, scaleY: 1 });
  result.sprite = sprite;
  result.rot = 0;
  result.scaleX = 1;
  result.scaleY = 1;
  if (sprite.spin) {
    const spin = state.spins.get(entity.entityId)?.get(spriteIndex);
    if (spin) {
      // The original never rotates the blade sprite: it compresses one axis by |cos(angle)|,
      // which reads as a turning blade while the art keeps its authored orientation.
      const scale = foreshorten(spin.angle);
      if (sprite.spin.axis === "y") {
        result.scaleX = scale;
      } else {
        result.scaleY = scale;
      }
    }
  }
  if (sprite.clips) {
    const player = state.frames.get(entity.entityId)?.sprites.get(spriteIndex);
    if (player) result.sprite = player.pose;
  }
  return result;
}

/** Advances the part's expression machine once and returns the clip it wants played. */
function stepEntityExpression(
  state: AnimationState,
  texture: PartTexture,
  entity: DrawEntity,
  totals: ReadonlyMap<number, BodyTotals>,
  dtSeconds: number,
): string | undefined {
  const expression = texture.expression;
  if (!expression) return undefined;
  const body = totals.get(entity.bodyId);
  const reference = speedReference(body?.thrust ?? 0, body?.mass ?? 0, expression.speedReference);
  return stepExpression(
    expressionOf(state, entity.entityId, state.random),
    expression,
    entity.vx,
    entity.vy,
    reference,
    dtSeconds,
  );
}

/**
 * Σ thrust of a body's active motors and Σ mass of all its parts. Mirrors the server: a motor
 * pushes with its content `thrustPerTick` unscaled (`GameRoom.RegisterPlacedRole`) while mass
 * grows with the cube of the part scale (`CompoundAssembler`), so vRef is the speed one second
 * of full thrust would reach.
 */
function collectBodyTotals(
  entities: readonly DrawEntity[],
  content: PartContentDocument | null,
): ReadonlyMap<number, BodyTotals> {
  BODY_TOTALS.clear();
  if (content === null) return BODY_TOTALS;
  PART_INDEX.clear();
  for (const part of content.parts) PART_INDEX.set(part.partTypeId, part);
  for (const entity of entities) {
    if (entity.bodyId === 0) continue;
    const part = PART_INDEX.get(entity.partTypeId);
    if (!part) continue;
    let totals = BODY_TOTALS.get(entity.bodyId);
    if (totals === undefined) {
      totals = { thrust: 0, mass: 0 };
      BODY_TOTALS.set(entity.bodyId, totals);
    }
    totals.mass += part.mass * entity.scale * entity.scale * entity.scale;
    if (entity.active && part.capabilities?.motor !== undefined) {
      totals.thrust += part.capabilities.motor.thrustPerTick;
    }
  }
  return BODY_TOTALS;
}

/** Mark and sweep: a snapshot that dropped an entity drops its animation with it. */
function sweepRemoved(state: AnimationState, entities: readonly DrawEntity[]): void {
  state.live.clear();
  for (const entity of entities) {
    if (entity.bodyId !== 0) state.live.add(entity.entityId);
  }
  for (const entityId of state.spins.keys()) {
    if (!state.live.has(entityId)) state.spins.delete(entityId);
  }
  for (const entityId of state.frames.keys()) {
    if (!state.live.has(entityId)) state.frames.delete(entityId);
  }
}

function entityFramesOf(state: AnimationState, entityId: number): EntityFrames {
  let frames = state.frames.get(entityId);
  if (frames === undefined) {
    frames = { sprites: new Map(), requestId: 0 };
    state.frames.set(entityId, frames);
  }
  return frames;
}

function spinOf(state: AnimationState, entityId: number, spriteIndex: number): SpinState {
  let spins = state.spins.get(entityId);
  if (spins === undefined) {
    spins = new Map();
    state.spins.set(entityId, spins);
  }
  let spin = spins.get(spriteIndex);
  if (spin === undefined) {
    spin = createSpinState();
    spins.set(spriteIndex, spin);
  }
  return spin;
}

function playerOf(state: AnimationState, entityId: number, spriteIndex: number, sprite: PartSprite): ClipPlayer {
  const frames = entityFramesOf(state, entityId);
  let player = frames.sprites.get(spriteIndex);
  if (player === undefined) {
    player = createClipPlayer(sprite, sprite.clips ?? {});
    frames.sprites.set(spriteIndex, player);
  }
  return player;
}

function expressionOf(
  state: AnimationState,
  entityId: number,
  random: () => number,
): ExpressionState {
  const frames = entityFramesOf(state, entityId);
  if (frames.expression === undefined) {
    frames.expression = createExpressionState(random);
  }
  return frames.expression;
}
