<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../PigForge.Physics.Abstractions/PigForge.Physics.Abstractions.csproj" />
    <PackageReference Include="JoltPhysicsSharp" Version="2.22.0" />
  </ItemGroup>

</Project>
